# Generated by Django 6.1.1 on 2026-09-30 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0003_itineraryparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='itineraryparticipant',
            constraint=models.UniqueConstraint(fields=('itinerary', 'user'), name='unique_itinerary_participant'),
        ),
    ]
