# Generated by Django 6.1.1 on 2026-09-30 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0001_initial"),
        ("itineraries", "0004_itineraryparticipant_unique_itinerary_participant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TripExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("accommodation", "Accommodation"),
                            ("activity", "Activity"),
                            ("transport", "Transport"),
                            ("food", "Food"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("expense_date", models.DateField()),
            ],
            options={
                "ordering": ["-expense_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="budget",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(fields=["user"], name="budgets_bud_user_id_f59062_idx"),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["created_at"], name="budgets_bud_created_42c3b2_idx"
            ),
        ),
        migrations.AddField(
            model_name="tripexpense",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="budgets.budget",
            ),
        ),
        migrations.AddField(
            model_name="tripexpense",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trip_expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="tripexpense",
            index=models.Index(
                fields=["budget"], name="budgets_tri_budget__ee3bf6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tripexpense",
            index=models.Index(
                fields=["category"], name="budgets_tri_categor_027158_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tripexpense",
            index=models.Index(
                fields=["expense_date"], name="budgets_tri_expense_3eff95_idx"
            ),
        ),
    ]
